/*
	Author:			Ayad Shammout
	Date:			10/19/2011
	Description:	Create Database Audit Specification
	
*/

USE DBName
GO

-- Replace the [xxxxxxx] with actual SQL Server Audit name

CREATE DATABASE AUDIT SPECIFICATION [DBName_DBAuditSpecs]
FOR SERVER AUDIT xxxxxxx
ADD (DATABASE_OPERATION_GROUP),
ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP),
ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),
ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP),
ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP),
ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP),
ADD (DATABASE_OBJECT_ACCESS_GROUP)
WITH (STATE = ON)
GO

-- DON'T FORGET TO ENABLE Server Audit Audit